<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-6J3RIMT" failures="1" tests="10" name="FinalProject.FinalProject.AppTest" time="70.347" errors="0" timestamp="2025-06-21T23:44:12 GMT+03:00" skipped="0">
  <testcase classname="FinalProject.FinalProject.AppTest" name="GetUrl" time="1.998"/>
  <system-out/>
  <testcase classname="FinalProject.FinalProject.AppTest" name="userRegistrationProsses" time="8.106"/>
  <system-out/>
  <testcase classname="FinalProject.FinalProject.AppTest" name="sign_in" time="7.538"/>
  <system-out/>
  <testcase classname="FinalProject.FinalProject.AppTest" name="productDetails" time="2.982"/>
  <system-out/>
  <testcase classname="FinalProject.FinalProject.AppTest" name="AddingProductstoCart" time="13.932"/>
  <system-out/>
  <testcase classname="FinalProject.FinalProject.AppTest" name="ViewingandModifyingtheCart" time="19.525"/>
  <system-out/>
  <testcase classname="FinalProject.FinalProject.AppTest" name="ProceedingtoCheckout" time="4.370"/>
  <system-out/>
  <testcase classname="FinalProject.FinalProject.AppTest" name="PrivacyPolicyAccessibility" time="3.697"/>
  <system-out/>
  <testcase classname="FinalProject.FinalProject.AppTest" name="ContactUsPage" time="3.280">
    <failure message="expected [contact us] but found [404 Not Found]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [contact us] but found [404 Not Found]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at FinalProject.FinalProject.AppTest.ContactUsPage(AppTest.java:171)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- ContactUsPage -->
  <system-out/>
  <testcase classname="FinalProject.FinalProject.AppTest" name="LogOut" time="4.919"/>
  <system-out/>
</testsuite> <!-- FinalProject.FinalProject.AppTest -->
